appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NnWpINpB26eicC1npKR6J7/+KzpQH+lwcss/w5xpag/p56RcviRmNcii/twEt5Rcog3FXIHTZs8pPBjZhAFablXAivIAkv3bKgwmK8+RdWqkiIC67I2FF+quHIgAzHeqW9u95ghGP7s6F7Xf5m0BRX5SkhOtD+0/0BLXdndmQBoUfg7T3YIKBYTEk9RAtFonp66mAyJ58Dx6ln8wIAVizNSqe97muncCProsTHniTKNwp9Lt1u6pIyy5S6FFmeK0SOL4wycKDFRk7vEReAhAxsViyIOHXrx1rtU22h3TldxSmezD8halOHz9mhh2LjCWSKmyxkaQu2jTbVFKVM4gRCTdi1nmEtqk+PLAx13Z55GC4Ld15DBpcdSthW22s9dWnV0EuSvucz7dkf0+jk0CqlVXfPF9q2xDfFn58WCnOlLGVa90B8KyhKsIcJJljxI+DL56p0eDEIm4Wn+S9oOjRCfiPfZR8jE5qd9LHNu8YefdT0wqQt6uM0/SQgctLwhELLXDeWJaiCDpxtC2vKb1hUn6K8+uHUyVSy9RjfeuDkiOs7AwwmKzQ4nG1csLaCiufwdMqbZDMSVgpsSB1WARhWVLr0pdNa/KTr6Dlde1ID+FBrazjaN/h9i7YYdHNbABopD/bsYaYjYqmovvXaIMyMXjmR4B7WDds424PNTq+zA=}
